name: tirth_industries
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_statusbarcolor: ^0.2.3
  firebase_core:
  flutter_inappwebview: ^5.3.2
  onesignal_flutter: ^2.6.3
  firebase_admob: ^0.11.0+2
  connectivity:
  shared_preferences:
  flutter_downloader: ^1.5.2
  path_provider:
  permission_handler:
  facebook_audience_network: ^0.9.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
